### PR TITLE
Proposal: optimized Dockerfile

### PR DESCRIPTION
**Pull request by oolfloo**
Hi, this is a small proposal for a "optimized" Dockerfile.
In my testing it reduces the size of the resulting image from 1.55GB to 415MB.

I have no issues and the docker-compose is starting as with the original one.

### CODE REVIEW

**Comment by oolfloo** [comment]
Related to #72

**Comment by Addono** [comment]
Hey! Thanks for the PR. LGTM 😄

**Comment by oolfloo** [comment]
That was almost to fast, I was just about to change the run-as user as well! :D

**Comment by Addono** [comment]
😄  You can create another PR if you feel like it.

When the changes are so small it's easy for me to review and merge them.

**Pull request merged**
