### PR TITLE
Internal networks and https support

### PR DESCRIPTION
**Pull request by techge**
This should make:

i) databases unavailable for host (which should be good e.g. in terms of security)
ii) optional ssl certs usable (does not crash without them); these needs to be put in folder certs

### CODE REVIEW

**Comment by techge** [comment]
as far as I can see the build is failing because of other commits...

**Comment by Addono** [comment]
Hi! Thanks for the PR! Sorry that I haven't come back to you earlier. Somehow I have to have discarded the message 😓

**Comment by Addono** [comment]
> as far as I can see the build is failing because of other commits...

Yeah, it's broken upstream. Don't worry about it.

**Comment by Addono** [comment]
With regard to your PR. I tried to touch the upstream source code as little as possible, as every change is going to make it more and more likely that at some point their implementation changes and hence requires maintenance down here.

Therefore, I would prefer to add SSL using a reverse proxy, e.g. NGINX or Apache, which runs as another container alongside the ones now already present. 

~One added benefit is that backwards compatibility is preserved, as the plain HTTP server is still available for anyone who wants to handle adding SSL themselves. Which is also important for anyone consuming the Docker image directly.~ _Edit: I stand corrected, if no certificate is passed you offer a default `http` server._

I tried looking online if there's an example of what I'm looking for, although most are way too complicated.

This post has the `docker-compose.yml` structure I was looking for, however their NGINX configuration "tries to do too much" (caching, serving static files):
https://dev.to/domysee/setting-up-a-reverse-proxy-with-nginx-and-docker-compose-29jg

This SO thread has a simpler NGINX configuration file, which would seem suitable.
https://stackoverflow.com/questions/47869317/docker-compose-nginx-ssl-reverse-proxy

**Comment by Addono** [comment]
I will close this one, as #17 and #18 should cover these changes.

**Pull request closed without merging**
